import type { TrainingScenario } from '../types';
import type { TrainingDifficulty } from '../hooks/useTraining';

export interface CurriculumLesson {
  id: string;
  title: string;
  concept: string;
  lessonBody: string;
  doSay: string[];
  dontSay: string[];
  objectives: string[];
  tip: string;
  scenario: TrainingScenario;
  subScenarioIndex: number;
  difficulty: TrainingDifficulty;
  passScore: number;
  minExchanges: number;
}

export interface CurriculumModule {
  id: string;
  title: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  color: 'green' | 'yellow' | 'red';
  lessons: CurriculumLesson[];
}

export const CURRICULUM: CurriculumModule[] = [
  // MODULE 1 - Cold Call Foundations (Beginner)
  {
    id: 'foundations',
    title: 'Cold Call Foundations',
    level: 'Beginner',
    color: 'green',
    lessons: [
      {
        id: 'f1-opener',
        title: 'The Perfect Opener',
        concept: 'Hook the prospect in the first 10 seconds with a relevance-first opening',
        lessonBody: `Prospects decide in 7 seconds whether to keep listening. The opener's job is not to pitch -- it's to earn 30 more seconds. Lead with a specific, credible reason why this call is relevant to them right now. End with a question, not a statement.`,
        doSay: [
          `"The reason I'm reaching out is I saw you just expanded your logistics team -- I work with ops leaders going through exactly that transition. Worth a quick minute?"`,
          `"I'll be quick -- we help SaaS teams reduce churn in the first 90 days. Is that something on your radar at all?"`,
          `"I noticed you're hiring three SDRs right now. I work with sales managers on the ramp-up side of that. Can I ask you one question?"`,
        ],
        dontSay: [
          `"Hi, how are you today?" -- it signals a sales call immediately and wastes credibility.`,
          `"I'm calling to tell you about our amazing product..." -- leading with your product before their problem loses them instantly.`,
          `"Do you have a quick minute to chat?" -- permission-asking openers hand control to the prospect before you've earned anything.`,
        ],
        objectives: [
          `Open without "how are you?" or any permission-asking filler`,
          `State a specific, credible reason why this call makes sense for them right now`,
          `End your opener with a curiosity-triggering question, not a pitch`,
        ],
        tip: `Your opening line decides everything. Skip the "how are you?" and lead with relevance -- a specific reason why this call makes sense for them right now. Prospects decide in 7 seconds whether to keep listening. Curiosity beats features every time.`,
        scenario: 'cold-opener',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 6.5,
        minExchanges: 4,
      },
      {
        id: 'f2-pattern-interrupt',
        title: 'The Pattern Interrupt',
        concept: `Break the "another cold call" pattern before the prospect mentally checks out`,
        lessonBody: `Every cold caller sounds identical. The prospect has a mental script for dismissing you before you finish your name. A pattern interrupt is anything that breaks that script -- directness, an unexpected question, or naming the awkwardness of the call itself. Specificity is your best weapon: the more tailored you sound, the harder you are to dismiss.`,
        doSay: [
          `"I know this is a cold call, so I'll be straight with you -- I have one question and you can decide from there if it's worth two minutes."`,
          `"This is a sales call, but it's a targeted one -- I only reach out to fintech ops teams and I think I have something specific for you."`,
          `"Most people I call tell me they're not interested after 10 seconds. Fair enough. But can I ask you the one question first?"`,
        ],
        dontSay: [
          `"Hi, my name is X and I'm calling from Y company..." -- the classic opener that triggers instant dismissal.`,
          `"I'm not here to waste your time..." -- this actually signals you're about to waste their time.`,
          `"You don't know me but..." -- leading with uncertainty gives the prospect permission to dismiss you.`,
        ],
        objectives: [
          `Avoid every cliche opener that triggers the "sales call" reflex`,
          `Use brevity and directness as a differentiator -- say more with less`,
          `Pivot quickly from the prospect's initial resistance to a genuine question`,
        ],
        tip: `Every cold caller sounds the same. A pattern interrupt is anything that sounds different from what they expect. Try leading with a bold statement, an unexpected question, or naming the awkwardness: "I know this is a cold call -- I'll be quick."`,
        scenario: 'cold-opener',
        subScenarioIndex: 1,
        difficulty: 'easy',
        passScore: 6.5,
        minExchanges: 4,
      },
      {
        id: 'f3-value-hook',
        title: 'The 10-Second Value Hook',
        concept: 'Compress your entire value proposition into one irresistible sentence',
        lessonBody: `You have one sentence to justify your existence on this call. The formula: "We help [specific person] who [struggle with X] achieve [outcome Y]." It must be specific, jargon-free, and create an instant mental picture of a before/after transformation. Test it: could a 10-year-old understand what you do?`,
        doSay: [
          `"We help e-commerce brands that are losing customers at checkout recover 20-30% of that revenue without touching their dev team."`,
          `"We work with HR managers at mid-size companies who are drowning in manual onboarding -- we automate the whole first-90-days process."`,
          `"We help sales managers whose reps are stuck in the 50-60% quota attainment range get them to 80%+ within a quarter."`,
        ],
        dontSay: [
          `"We're an AI-powered, omnichannel, end-to-end solution for enterprise growth..." -- jargon stacking kills the hook.`,
          `"We do a lot of things -- CRM, analytics, automation, integrations..." -- listing features is not a value prop.`,
          `"We basically help companies do better sales stuff." -- vagueness signals you don't understand your own product.`,
        ],
        objectives: [
          `State who you help, what problem you solve, and the outcome -- in one sentence`,
          `Avoid jargon, acronyms, and feature-listing in your hook`,
          `Deliver the hook with enough confidence that the prospect wants to hear more`,
        ],
        tip: `You have one sentence to justify your existence on this call. The formula: "We help [specific type of person] who [struggle with X] to [achieve outcome Y]." Practice until it sounds natural, not rehearsed.`,
        scenario: 'cold-opener',
        subScenarioIndex: 2,
        difficulty: 'easy',
        passScore: 6.5,
        minExchanges: 4,
      },
      {
        id: 'f4-not-interested',
        title: 'Handling "Not Interested"',
        concept: 'Turn the first rejection into the real start of the conversation',
        lessonBody: `"Not interested" is a reflex, not a decision -- the prospect says it before they even know what you're offering. Don't argue, don't apologize, and don't dump more information. The move is to acknowledge it and use a pivot question that earns 30 more seconds without any pressure.`,
        doSay: [
          `"That's completely fair -- I won't push. Can I ask just one quick question before I let you go?"`,
          `"Most people feel that way at first. I get it. If I can ask you one thing, and it doesn't land, I'll hang up right now."`,
          `"Totally understand. Not every call is relevant. Can I ask -- is it timing, or is the problem I'm solving just not on your radar?"`,
        ],
        dontSay: [
          `"But wait -- just hear me out for two minutes!" -- pushing after a rejection signals you won't respect their time.`,
          `"I understand, but our product is really great and..." -- launching into a pitch after rejection escalates resistance.`,
          `"Oh okay, sorry to bother you." -- caving immediately gives up any chance of a real conversation.`,
        ],
        objectives: [
          `Acknowledge the objection without arguing or apologizing`,
          `Use a pivot question that earns 30 more seconds without pressure`,
          `Reframe the call from a pitch to a quick discovery conversation`,
        ],
        tip: `"Not interested" is a reflex, not a decision. Most prospects say it before they even know what you're offering. Don't fight it -- flow with it: "That's fair, and I won't take much of your time. Most people I talk to felt the same until I asked them one question."`,
        scenario: 'not-interested',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'f5-curiosity-pivot',
        title: 'The Curiosity Question Pivot',
        concept: 'Replace defensiveness with curiosity to keep the prospect talking',
        lessonBody: `When a prospect resists, amateurs get defensive and talk more. Professionals get curious and ask better questions. The goal of the curiosity pivot is to make the prospect think -- a question they haven't been asked before naturally invites an answer. Use their response to guide the entire rest of the conversation.`,
        doSay: [
          `"What would have to be different for a call like this to be worth your time?"`,
          `"Can I ask -- what does your team currently do when [the problem I solve] comes up?"`,
          `"I'm curious -- is it the timing, or is this genuinely not a priority for your business right now?"`,
        ],
        dontSay: [
          `"But we have clients just like you who saw great results..." -- jumping to social proof before they've expressed any interest.`,
          `"Can I at least schedule a follow-up?" -- asking for a next step before they're engaged builds resentment.`,
          `"I just want to tell you about one quick feature..." -- a feature pitch when they're disengaged goes nowhere.`,
        ],
        objectives: [
          `Ask an open-ended question that genuinely interests the prospect in themselves`,
          `Transition from opener to discovery without the prospect noticing the shift`,
          `Demonstrate that you researched them or their situation before calling`,
        ],
        tip: `The best salespeople are genuinely curious. When a prospect resists, the amateur gets defensive; the professional gets curious. "What's the one thing that would have to be different for a conversation like this to be worth your time?" is a powerful pivot -- it makes them think.`,
        scenario: 'not-interested',
        subScenarioIndex: 1,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'f6-reading-energy',
        title: 'Reading Prospect Energy',
        concept: 'Match your pacing and tone to the emotional state of the prospect',
        lessonBody: `Tone is data. A rushed prospect needs a faster, more concise pitch. A skeptical one needs patience and questions, not more information. Mirroring -- matching their pace, energy and brevity -- is the fastest way to build rapport without them noticing. The biggest mistake is delivering the same scripted energy regardless of how the prospect sounds.`,
        doSay: [
          `If they sound rushed: "I'll keep this under 60 seconds -- [hook] -- does that land at all?"`,
          `If they sound skeptical: "I can hear the hesitation -- fair. What would make this worth a conversation for you?"`,
          `If they sound open: slow down, be conversational -- "Tell me a bit about how your team handles that right now."`,
        ],
        dontSay: [
          `Delivering your full pitch at full speed to a rushed prospect -- they'll hang up mid-sentence.`,
          `Being upbeat and chatty with a hostile prospect -- it reads as oblivious and increases friction.`,
          `"Sorry, I'll be quick" -- apologising for the call every other sentence drains your authority.`,
        ],
        objectives: [
          `Identify whether the prospect is rushed, skeptical, curious, or open within the first exchange`,
          `Adjust your speaking pace and energy to mirror theirs within 2 exchanges`,
          `Use the prospect's tone as a guide for how much time you have and what to say`,
        ],
        tip: `Tone is data. A rushed prospect needs a faster, more concise pitch. A skeptical one needs patience and questions, not more talking. Mirroring is the fastest way to build rapport: if they're brief, be brief. Adapt or lose them.`,
        scenario: 'cold-opener',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'f7-thirty-second-pitch',
        title: 'The 30-Second Pitch',
        concept: 'Deliver a compelling, complete pitch that earns a real response',
        lessonBody: `A 30-second pitch is not a features dump -- it's a micro-story with a beginning (their problem), middle (how you solve it), and end (the result). Always close with a tie-down question that checks whether the problem resonates. This turns a monologue into a dialogue and is the signal that separates pros from amateurs.`,
        doSay: [
          `"Companies like yours usually struggle with [X]. We built [product] specifically for that -- and teams typically see [outcome] within 90 days. Does that match anything you're dealing with?"`,
          `"Here's the short version: [problem], [how we fix it], [result]. We've done it for [similar customer]. Is that relevant to your situation at all?"`,
          `"In 30 seconds: we solve [X] for [type of team]. You end up with [outcome] and without [painful tradeoff]. Does that sound like a problem you'd want solved?"`,
        ],
        dontSay: [
          `"We have over 200 features including dashboards, integrations, API access, white labelling..." -- features without context don't mean anything.`,
          `"We're the number one platform in our category..." -- claims without specifics are dismissed immediately.`,
          `Pitching for 3 minutes straight without asking a question -- you've lost them after 30 seconds.`,
        ],
        objectives: [
          `Cover problem, solution, and outcome in under 30 seconds`,
          `End with a tie-down question that checks if the problem resonates with them`,
          `Adjust the pitch based on what you already learned from the opener`,
        ],
        tip: `A 30-second pitch is not a features dump -- it's a story with a beginning (their problem), middle (how you solve it), and end (the result others have gotten). Always end with a checking question: "Does that resonate at all with what you're dealing with?"`,
        scenario: 'cold-opener',
        subScenarioIndex: 1,
        difficulty: 'medium',
        passScore: 7.0,
        minExchanges: 5,
      },
      {
        id: 'f8-skeptic',
        title: 'The Skeptical Prospect',
        concept: `Turn a skeptic's resistance into a productive diagnostic conversation`,
        lessonBody: `A skeptical prospect is still on the phone -- that's actually a good sign. The mistake is trying to overwhelm skepticism with more facts, more features, or stronger claims. Skeptics respond to honesty, specificity, and a question that makes them feel heard. Demonstrating you know something specific about their world credentials you far more than any product claim.`,
        doSay: [
          `"I appreciate the skepticism -- what would you need to see for this to even be worth a 15-minute call?"`,
          `"Fair enough. I'll be specific: we helped [similar company] go from [X] to [Y] in [timeframe]. Is that the kind of result that would be relevant to you?"`,
          `"I don't blame you -- there are a lot of tools making big claims. What's been the frustration with the ones you've tried before?"`,
        ],
        dontSay: [
          `"I know you're skeptical, but if you just give me 10 minutes I can explain everything..." -- responding to skepticism with more volume is the worst move.`,
          `"We're completely different from everything else out there." -- unsubstantiated differentiation claims to a skeptic feel like more of the same.`,
          `"Trust me, our customers love us." -- appealing to trust when they've expressed skepticism backfires.`,
        ],
        objectives: [
          `Resist the urge to "prove yourself" by dumping more information`,
          `Use the skeptic's pushback as a trigger to ask a deeper question`,
          `Demonstrate credibility through specificity, not through claims`,
        ],
        tip: `A skeptical prospect is still on the phone -- that's a good sign. The mistake is trying to overwhelm skepticism with more facts. Instead, lean into it: "I appreciate that -- what would you need to see for something like this to even be worth a 15-minute call?"`,
        scenario: 'cold-opener',
        subScenarioIndex: 1,
        difficulty: 'medium',
        passScore: 7.0,
        minExchanges: 5,
      },
      {
        id: 'f9-hostile',
        title: 'Surviving Immediate Hostility',
        concept: 'Stay grounded and composed when a prospect is actively trying to end the call',
        lessonBody: `Hostile prospects test your composure -- and composure is what gets you through it. Apologising, getting flustered, or matching their energy all confirm you're worth dismissing. Stay calm, stay brief, and give them one non-pressuring option to stay. If they decline, disengage with grace -- how you exit determines whether a future call is possible.`,
        doSay: [
          `"Fair enough -- I won't push. Out of curiosity, is it cold calls in general or just not relevant to you right now?"`,
          `"Understood. I'll let you go. If anything changes on the [problem] side, my name is [name] and I'm easy to find."`,
          `"No problem at all. Last thing -- can I ask what would have to change for this to be worth a 5-minute call someday?"`,
        ],
        dontSay: [
          `"I'm so sorry for bothering you!" -- excessive apology confirms you had no right to call.`,
          `"Just give me two minutes, I promise it'll be worth it!" -- begging after hostility kills any future chance.`,
          `Arguing back or getting defensive -- matching hostile energy makes both of you look bad.`,
        ],
        objectives: [
          `Remain calm and professional under verbal pressure -- no defensiveness or apology`,
          `Use one controlled, non-pressuring response to give the prospect a way to stay without losing face`,
          `Know when to end gracefully rather than escalate -- closing well is also a win`,
        ],
        tip: `Hostile prospects test your composure. The worst response is to apologize or get flustered. The best response is calm, brief, and slightly unexpected: "Fair enough -- I won't push. But out of curiosity, is it cold calls in general or is it because this isn't relevant to you right now?"`,
        scenario: 'not-interested',
        subScenarioIndex: 2,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
    ],
  },

  // MODULE 2 - Objection Handling (Intermediate)
  {
    id: 'objections',
    title: 'Objection Handling',
    level: 'Intermediate',
    color: 'yellow',
    lessons: [
      {
        id: 'o1-framework',
        title: 'The Objection Framework',
        concept: 'Master the universal Acknowledge, Explore, Respond pattern',
        lessonBody: `Most reps fail objection handling because they skip the first step: acknowledging. When you immediately defend or counter, the prospect feels unheard and digs in harder. The framework is: (1) Acknowledge the concern as valid, (2) Explore with a clarifying question to find the real issue, (3) Respond only after you truly understand what's behind the objection. In that order, every time.`,
        doSay: [
          `"That's a fair point -- I want to make sure I understand it before I respond. What specifically is driving that concern?"`,
          `"I hear you. A lot of people bring that up. Can I ask what's behind it for you in particular?"`,
          `"Totally makes sense. Before I address it -- is that the main thing, or is there something else under that?"`,
        ],
        dontSay: [
          `"Actually, that's not really an issue because..." -- countering immediately without acknowledgment makes them defensive.`,
          `"I understand, BUT..." -- the word "but" negates everything before it. Replace with "and" or just pause.`,
          `Launching into a 3-minute rebuttal before asking a single question -- you're answering the wrong objection.`,
        ],
        objectives: [
          `Always acknowledge the objection before responding -- never skip this step`,
          `Ask a clarifying question to uncover the real concern beneath the stated one`,
          `Respond only after you truly understand what's behind the objection`,
        ],
        tip: `Most reps fail objection handling because they skip the first step: acknowledging. When you immediately defend or counter, the prospect feels unheard and digs in harder. The framework is: Acknowledge, Explore, Respond. In that order, every time.`,
        scenario: 'price-objection',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'o2-price-basic',
        title: 'Price Objections: Defending Value',
        concept: `Reframe cost as ROI before the prospect compares you to a cheaper alternative`,
        lessonBody: `Price objections are almost always value objections in disguise. Before defending the price, isolate what's really driving it. Then shift the conversation entirely to outcomes: what does solving this problem actually worth? When the value is 10x the price, cost stops being the conversation. Never discount before you've fully explored the value gap.`,
        doSay: [
          `"Is it that the price is too high, or are you not confident you'll see the return on it?"`,
          `"If this solves the problem we talked about, what would that be worth to your team in a year?"`,
          `"The cost I'd actually focus on is what staying in the current situation costs you -- can we put a number on that?"`,
        ],
        dontSay: [
          `"I can probably get you a discount if that helps..." -- discounting immediately destroys your price credibility.`,
          `"Our pricing is actually very competitive for the market." -- defending the price without addressing their value concern misses the point.`,
          `"It's expensive but worth it, trust me." -- asserting value without evidence doesn't land.`,
        ],
        objectives: [
          `Isolate whether the objection is about price or about perceived value`,
          `Quantify the cost of the problem they're trying to solve -- not the cost of your solution`,
          `Use a concrete ROI statement tied to their specific situation`,
        ],
        tip: `Price objections are almost always value objections in disguise. Before defending the price, isolate it: "Is it that the price is too high, or are you not sure you'll see the return?" Then shift the conversation entirely to outcomes.`,
        scenario: 'price-objection',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'o3-send-info',
        title: '"Send Me Info" -- The Soft Brush-Off',
        concept: 'Convert the email deflection into a scheduled, committed next step',
        lessonBody: `"Send me some info" is usually a polite way to end the call -- not a genuine request. The fatal mistake is agreeing and hanging up; you'll never hear from them again. The move is to use the request to buy 2 minutes of real discovery, then lock in a specific follow-up call before you send anything. No scheduled call, no email.`,
        doSay: [
          `"I can definitely do that -- I want to make sure I send you the right thing. Can I ask two quick questions so it's actually relevant to you?"`,
          `"Happy to. Can we also lock in 15 minutes next Thursday so we can walk through it together? Otherwise info tends to get lost."`,
          `"Before I send anything -- what's the one thing you'd want it to answer for you?"`,
        ],
        dontSay: [
          `"Sure! I'll send it over now." -- agreeing immediately ends the call and kills the deal.`,
          `"I'll send you our full product brochure and pricing sheet." -- generic materials with no context never get read.`,
          `"I'll follow up next week to see if you had a chance to look." -- vague follow-ups without a committed time slot go nowhere.`,
        ],
        objectives: [
          `Identify whether the email request is genuine or a polite exit`,
          `Never send info without a committed follow-up meeting first`,
          `Create a specific reason why a call is more valuable than an email right now`,
        ],
        tip: `"Send me some info" is usually a polite way to end the call. The fatal mistake is saying "Sure!" and hanging up -- you'll never hear from them again. Use the request to buy 2 more minutes of discovery, then lock in a follow-up call before you send anything.`,
        scenario: 'send-me-info',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'o4-think-it-over',
        title: '"I\'ll Think It Over" -- Creating Real Urgency',
        concept: 'Surface the hidden concern and create genuine urgency without pressure tactics',
        lessonBody: `"I'll think about it" means you haven't made the cost of inaction feel real yet. Don't accept it at face value -- explore what they're actually thinking about. Then introduce time-based cost: what does staying in the current situation cost per week, per month, per quarter? When the delay itself has a price tag, thinking it over becomes expensive.`,
        doSay: [
          `"Of course -- what specifically would you be thinking through? I want to make sure I've answered the right questions."`,
          `"That's fine. I'd hate for you to come back to it in 3 months and realise [cost of delay]. What's a realistic timeline for you?"`,
          `"I respect that. Most people in your position want to feel certain before committing. What would certain look like for you?"`,
        ],
        dontSay: [
          `"No problem, take all the time you need!" -- open-ended thinking is a deal in limbo.`,
          `"This offer is only available until Friday." -- fake urgency is transparent and destroys trust.`,
          `"I'll check back in a few weeks." -- no specific timeframe, no commitment.`,
        ],
        objectives: [
          `Never accept "I'll think about it" without exploring what they're actually thinking about`,
          `Ask a specific question to surface the real blocker`,
          `Create urgency through the cost of delay, not through artificial scarcity or pressure`,
        ],
        tip: `"I'll think about it" means you haven't made the cost of inaction feel real yet. Don't pressure -- explore it: "What specifically would you be thinking through?" Then introduce time-based cost. When the delay itself has a price tag, thinking it over becomes expensive.`,
        scenario: 'think-it-over',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'o5-budget',
        title: 'The Budget Blocker',
        concept: 'Navigate real budget constraints without killing the deal or discounting prematurely',
        lessonBody: `When someone says they don't have budget, ask whether it's a timing issue or a real ceiling. Real budget constraints often have workarounds -- phased implementation, different billing cycles, or reallocating from another line item. But none of that matters until you've rebuilt the ROI case. If the value is there, budget finds a way.`,
        doSay: [
          `"Is that a timing issue, or is it a hard ceiling? I ask because we have a few ways to structure this."`,
          `"If this gets you [outcome], how does that compare to what you're currently spending on [the problem]?"`,
          `"Would it help if we phased the rollout so the cost was spread across two quarters?"`,
        ],
        dontSay: [
          `"I'm sure we can work something out on price." -- rushing to discount before exploring options weakens your position.`,
          `"Budget shouldn't be the reason you miss out on this." -- pressure framing after a real constraint lands badly.`,
          `"That's okay, just let me know when the budget opens up." -- surrendering without exploring solutions kills deals.`,
        ],
        objectives: [
          `Distinguish between "no budget" as a real constraint versus a negotiating tactic`,
          `Explore creative structuring options before accepting budget as a final barrier`,
          `Help the prospect build the internal case for budget reallocation if the ROI warrants it`,
        ],
        tip: `When someone says they don't have budget, ask: "Is that a timing issue or a budget ceiling?" Real budget constraints often have workarounds -- phased implementation, different billing structures, or reallocating from another line item. If the value is there, budget finds a way.`,
        scenario: 'price-objection',
        subScenarioIndex: 1,
        difficulty: 'medium',
        passScore: 7.0,
        minExchanges: 5,
      },
      {
        id: 'o6-status-quo',
        title: 'Breaking the Status Quo',
        concept: 'Make staying the same feel riskier than making a change',
        lessonBody: `Comfortable people don't change. Your job isn't to convince them your product is great -- it's to make the cost of staying put feel real. Get them to name the problem, quantify its cost, and then project forward: what does this look like in a year if nothing changes? When "doing nothing" becomes an active, costly choice rather than a safe default, the decision shifts.`,
        doSay: [
          `"How long has [the problem] been going on? And what's the cumulative cost -- time, money, headcount -- of keeping it the way it is?"`,
          `"If nothing changes over the next 12 months, what does that look like for your team?"`,
          `"What's the risk to your business of staying with the current setup?"`,
        ],
        dontSay: [
          `"Your current solution is outdated." -- attacking their existing setup creates defensiveness, not openness.`,
          `"Everyone is moving to [your solution]." -- FOMO tactics without substance don't work on confident buyers.`,
          `"You're losing money by not switching." -- stating their problem without asking about it feels presumptuous.`,
        ],
        objectives: [
          `Quantify the real cost of the prospect's current situation -- financially or operationally`,
          `Make the "do nothing" option feel like an active, costly choice -- not a safe default`,
          `Use future-pacing to paint a specific picture of what staying put looks like in 12 months`,
        ],
        tip: `Comfortable people don't change. Your job isn't to convince them your product is great -- it's to make the cost of staying put feel real. Start by getting them to name the problem, then amplify the cost, then project forward.`,
        scenario: 'not-interested',
        subScenarioIndex: 1,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
      {
        id: 'o7-competitor',
        title: 'Winning the Competitor Comparison',
        concept: 'Differentiate on value when a competitor is cheaper -- without badmouthing them',
        lessonBody: `When a prospect names a cheaper competitor, the amateur gets defensive. The professional gets curious. Find out what they actually value before comparing anything. Then differentiate on the dimension you own -- not price. Reframe the buying decision from cost-per-feature to total outcome and risk. Let their known weaknesses come up through questions, not attacks.`,
        doSay: [
          `"What is it about [competitor] that's appealing to you?" -- then listen carefully.`,
          `"How important to you is [your key differentiator]? I ask because that's where we tend to separate."`,
          `"What happens if [competitor's known weakness] becomes an issue down the line -- is that a risk you're comfortable with?"`,
        ],
        dontSay: [
          `"[Competitor] is actually not that good -- they have a lot of issues." -- badmouthing competitors is unprofessional and backfires.`,
          `"We're better in every way." -- vague superiority claims without specifics aren't believable.`,
          `"Match their price? Let me check what I can do." -- immediately trying to price-match shows you have nothing else to offer.`,
        ],
        objectives: [
          `Never speak negatively about a competitor -- pivot to differentiation through questions`,
          `Identify what the prospect actually values most before comparing features`,
          `Reframe the buying decision from price-per-feature to total outcome and risk`,
        ],
        tip: `When a prospect names a cheaper competitor, get curious: "What is it about [competitor] that appeals to you?" Listen. Then find the gaps. Position your price as the premium for a specific, measurable outcome. Let their weaknesses come up through questions, not attacks.`,
        scenario: 'price-objection',
        subScenarioIndex: 2,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
      {
        id: 'o8-multi-stakeholder',
        title: 'The Multi-Stakeholder Stall',
        concept: `Turn "I need to check with my team" into a jointly-managed next step`,
        lessonBody: `"I need to check with my team" is a real blocker -- but it's also an opportunity. Find out who the stakeholders are and what they care about. Then arm your champion with the right framing to sell internally on your behalf. Never let this call end without a specific next step that includes the other decision makers.`,
        doSay: [
          `"Who else will weigh in on this, and what are they typically focused on -- cost, risk, implementation?"`,
          `"What if I put together a one-pager addressing their specific concerns? You'd walk in with answers, not questions."`,
          `"Let's get a 30-minute call on the calendar with you and your team -- I'll handle their questions directly."`,
        ],
        dontSay: [
          `"Sure, just let me know what they say." -- an open-ended wait is a deal killer.`,
          `"Can you just forward them our website?" -- generic materials are not a substitute for a managed next step.`,
          `"Is your manager the real decision maker here?" -- questioning their authority damages the relationship.`,
        ],
        objectives: [
          `Understand who the other stakeholders are and what their concerns might be`,
          `Arm the prospect to sell internally on your behalf with the right framing`,
          `Set a specific, committed next step that includes the other decision makers`,
        ],
        tip: `"I need to check with my team" is a real blocker -- but also an opportunity. Find out who the stakeholders are and what they care about. Arm your champion: "What if I put together a one-pager addressing their concerns?" Always schedule the multi-stakeholder call before hanging up.`,
        scenario: 'think-it-over',
        subScenarioIndex: 1,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
      {
        id: 'o9-serial-objector',
        title: 'The Serial Objector',
        concept: 'Recognize and neutralize the pattern of layered objections before it stalls the deal indefinitely',
        lessonBody: `Serial objectors raise a new concern every time you address the last one. The mistake is answering each one in sequence -- it rewards the pattern and signals that more objections will buy more time. Instead, name the pattern professionally and force a binary moment: either there's a deal here or there isn't. Clarity is more valuable than one more rebuttal.`,
        doSay: [
          `"I want to be direct -- we've worked through pricing, timing, and the team sign-off. If all of those were resolved, is this something you'd actually move forward with?"`,
          `"It feels like every time we address one concern, another one comes up. I'd rather find the real blocker than keep going in circles -- what's actually holding you back?"`,
          `"Let me ask you directly: is there a world where you buy this, or are we at a dead end?"`,
        ],
        dontSay: [
          `Patiently addressing objection #4, #5, #6 in sequence -- you're training them to keep stalling.`,
          `"I understand, let me address that concern as well..." -- infinite patience for infinite objections is not a strategy.`,
          `Giving up and asking to "reconnect next quarter" -- without naming the pattern, nothing will be different next quarter.`,
        ],
        objectives: [
          `Recognize when objections are a pattern, not individual concerns to be addressed one-by-one`,
          `Call out the pattern professionally and redirect to the real decision point`,
          `Force a moment of clarity -- either there's a deal here or there isn't`,
        ],
        tip: `Serial objectors raise a new concern every time you address the last one. Stop answering each one. Name it: "We've worked through pricing, timing, and your team's concerns. At this point, if those were all resolved, is this something you'd actually move forward with?" This forces a binary moment.`,
        scenario: 'think-it-over',
        subScenarioIndex: 2,
        difficulty: 'hard',
        passScore: 8.0,
        minExchanges: 6,
      },
    ],
  },

  // MODULE 3 - Discovery & Closing (Advanced)
  {
    id: 'closing',
    title: 'Discovery & Closing',
    level: 'Advanced',
    color: 'red',
    lessons: [
      {
        id: 'c1-situation',
        title: 'Situation Questions That Build Context',
        concept: 'Gather the essential facts without turning discovery into an interrogation',
        lessonBody: `Situation questions establish context, but they drain energy if you ask too many. Only ask what you genuinely don't know and can't find beforehand. Structure them to flow naturally -- each answer should lead to the next question, not to a checkbox on a list. Aim for 2-3 max before transitioning to the problem.`,
        doSay: [
          `"You're currently handling [X] with [what we know about them] -- how is that working for your team day-to-day?"`,
          `"Before I assume anything, can I ask how you're currently managing [process]?"`,
          `"How many people are involved in this process on your side? I want to make sure I understand the scope."`,
        ],
        dontSay: [
          `"So, can you tell me about your company?" -- questions you could have Googled signal you haven't prepared.`,
          `"What's your budget, your timeline, and who else is involved?" -- stacking three questions at once overwhelms and feels like an intake form.`,
          `"Do you currently use any tools for this?" -- yes/no questions end conversations instead of opening them.`,
        ],
        objectives: [
          `Ask situation questions that are specific and pre-researched -- avoid questions you could have Googled`,
          `Use each answer to naturally transition to the next question, not check a list`,
          `Establish context for the problem you already know they likely have`,
        ],
        tip: `Situation questions establish context, but they drain energy if you ask too many. Only ask what you genuinely don't know. Structure them to flow naturally: each answer leads to the next question. Aim for 2-3 max before transitioning to problem questions.`,
        scenario: 'discovery',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'c2-problem',
        title: 'Problem Questions That Uncover Pain',
        concept: 'Ask questions that make the prospect articulate their own pain in their own words',
        lessonBody: `People act on problems they've articulated out loud, not problems someone told them they have. Your job is to ask questions that make the prospect say the problem in their own words. Then follow up to quantify it. When they've named it twice and put a number on it, the pain is real to them -- and they own it.`,
        doSay: [
          `"What's the most frustrating part of how you handle that today?"`,
          `"When that breaks down, how often does it happen -- and what does it cost you when it does?"`,
          `"Is that something your team has tried to fix before? What happened?"`,
        ],
        dontSay: [
          `"So you're probably experiencing [problem] -- right?" -- leading them to your conclusion skips the discovery.`,
          `"I bet you have issues with [X]." -- assuming their pain without asking is presumptuous and often wrong.`,
          `"Do you have any challenges?" -- too broad; gives them permission to say "no, we're fine".`,
        ],
        objectives: [
          `Guide the prospect to name the problem themselves -- don't name it for them`,
          `Ask about problems adjacent to your solution, not just the obvious ones`,
          `Use follow-up questions to quantify the problem's impact before moving on`,
        ],
        tip: `People act on problems they've articulated out loud, not problems someone told them they have. Your job is to ask questions that make the prospect say the problem in their own words. Then quantify: "How often does that happen? What does it cost you when it does?"`,
        scenario: 'discovery',
        subScenarioIndex: 0,
        difficulty: 'easy',
        passScore: 7.0,
        minExchanges: 4,
      },
      {
        id: 'c3-implication',
        title: 'Implication Questions That Amplify Pain',
        concept: 'Expand the impact of the problem beyond the obvious to create real urgency',
        lessonBody: `Implication questions are the most powerful in discovery because they transform a small problem into a business-level urgency. Start from the problem they named and cascade: "When [problem] happens, what does that mean for [downstream process]?" Each question forces them to trace the consequences further. By the end, they've sold themselves on why this can't wait.`,
        doSay: [
          `"When [problem] happens, what does that mean for [downstream team or process]?"`,
          `"And when that breaks down -- what's the impact on revenue, headcount, or customers?"`,
          `"If this keeps going for another year, what does that look like for the business?"`,
        ],
        dontSay: [
          `"So that means you're basically losing thousands of dollars a week." -- quantifying for them feels presumptuous; let them calculate it.`,
          `"That's a really serious problem." -- editorialising their problem makes you seem like you're selling, not listening.`,
          `Moving straight to your solution after the first problem is named -- you haven't amplified anything yet.`,
        ],
        objectives: [
          `Connect the problem to downstream consequences the prospect may not have considered`,
          `Ask implication questions that link to business outcomes: revenue, costs, time, or risk`,
          `Let the prospect calculate the full cost of the problem themselves`,
        ],
        tip: `Implication questions transform a small problem into a business-level urgency. Start from the problem they named and cascade the consequences: "When that happens, what does it mean for X? And when X breaks down, what's the impact on Y?" Let them calculate the full cost themselves.`,
        scenario: 'discovery',
        subScenarioIndex: 1,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
      {
        id: 'c4-guarded',
        title: 'Discovery with the Guarded Prospect',
        concept: 'Extract meaningful information from a prospect who answers every question minimally',
        lessonBody: `Guarded prospects give short answers because they're protecting themselves from being sold to. Asking harder questions or giving up are both mistakes. Instead, make it easy to elaborate: use silence after a short answer, switch to peer benchmarking ("a lot of teams I work with..."), and reframe from interrogation to collaborative problem-solving.`,
        doSay: [
          `After a short answer: "Tell me more about that." -- then wait. Silence invites elaboration.`,
          `"A lot of teams I work with in your space struggle with [X] -- does any of that sound familiar?"`,
          `"I'm not trying to pitch you -- I'm trying to understand if there's even a fit. What would be most relevant to you right now?"`,
        ],
        dontSay: [
          `Filling every silence with more questions -- it feels like an interrogation.`,
          `"Come on, you can share more than that." -- pressuring a guarded prospect closes them down further.`,
          `Giving up after two short answers and moving to the pitch -- you haven't earned enough to pitch yet.`,
        ],
        objectives: [
          `Break through one-word answers with follow-up probes that make it easy to elaborate`,
          `Use silence strategically -- resist the urge to fill the gap after a minimal answer`,
          `Reframe questions from interrogation-style to collaborative problem-solving`,
        ],
        tip: `Guarded prospects give short answers because they're protecting themselves. The mistake is asking harder questions or giving up. Instead, try: "Tell me more about that" -- then wait. Reframe from "What's your problem?" to "A lot of teams I work with struggle with X -- does that sound familiar?"`,
        scenario: 'discovery',
        subScenarioIndex: 1,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
      {
        id: 'c5-need-payoff',
        title: 'Need-Payoff Questions That Close the Loop',
        concept: 'Guide the prospect to articulate the value of solving the problem in their own words',
        lessonBody: `Need-payoff questions are the final move in discovery: they get the prospect to build the ROI case for you. "If you could solve [problem] in 90 days, what would that mean for your team?" When they answer, they've just described the value of your solution in their own words. Mirror those words back in your pitch -- nothing is more persuasive than someone's own language.`,
        doSay: [
          `"If you could solve [problem] in 90 days, what would that mean for your team?"`,
          `"What would a solution be worth to you if it delivered [the outcome they described]?"`,
          `"How much of your team's time is this currently eating up -- and what could they do with that time back?"`,
        ],
        dontSay: [
          `"So based on all that, it sounds like you should definitely go with us." -- rushing to the close before they've valued the solution.`,
          `"Our product would save you about $50,000 a year." -- quantifying for them without letting them arrive at their own number.`,
          `Moving from problem questions straight to the pitch -- the payoff question is the bridge; skip it and the pitch lands cold.`,
        ],
        objectives: [
          `Ask the prospect to describe their ideal outcome -- not the features they want`,
          `Get them to quantify the value of solving the problem before you name a price`,
          `Use their answer as the foundation for your solution presentation`,
        ],
        tip: `Need-payoff questions get the prospect to sell themselves. "If you could solve [problem] in 90 days, what would that mean for your team?" When they answer, they've built the ROI case for you. Write down their exact words and mirror them back in your pitch.`,
        scenario: 'discovery',
        subScenarioIndex: 2,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
      {
        id: 'c6-trial-close',
        title: 'The Trial Close',
        concept: `Test for commitment without asking "do you want to buy?" and hear the real objections`,
        lessonBody: `A trial close is not "are you ready to buy?" -- it's "does this solve the problem we talked about?" If they say yes, you're already in the close. If they hesitate, you've surfaced an objection before it becomes a deal-breaker. The trial close is the diagnostic tool that tells you exactly what's left to address.`,
        doSay: [
          `"Based on what we've covered, does this feel like a fit for what you're trying to solve?"`,
          `"If the logistics work out, is this the direction you want to go?"`,
          `"Does this solve the problem, or are there still pieces that don't add up for you?"`,
        ],
        dontSay: [
          `"Are you ready to get started today?" -- this is the hard close, not the trial close; it skips the diagnostic step.`,
          `"So, shall I send over the contract?" -- moving to paperwork before confirming fit creates resistance.`,
          `"You're basically sold at this point, right?" -- assuming commitment before testing for it is overconfident and off-putting.`,
        ],
        objectives: [
          `Use a trial close question to test temperature before presenting formal options`,
          `Listen for hesitation in their "yes" -- that's where the real objection lives`,
          `Move from a soft yes to a specific, committed next step in the same exchange`,
        ],
        tip: `A trial close is not "are you ready to buy?" -- it's "does this solve the problem we talked about?" If they say yes, you're already in the close. If they hesitate, you've surfaced an objection before it becomes a deal-breaker.`,
        scenario: 'closing',
        subScenarioIndex: 0,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
      {
        id: 'c7-cold-feet',
        title: 'Resolving Last-Minute Cold Feet',
        concept: 'Diagnose and defuse the vague hesitation that appears right before a deal closes',
        lessonBody: `Last-minute cold feet usually isn't about the product -- it's about the risk of being wrong. The prospect is afraid of making a bad decision, looking foolish, or disrupting what's working. The best response is to make the decision feel safer, not to add more pressure. Reduce the perceived risk of saying yes, and the hesitation dissolves.`,
        doSay: [
          `"What's the specific thing you're hesitant about? I want you going in with full confidence, not just agreeing to move forward."`,
          `"A lot of people feel this at the last step -- can I share how [similar customer] felt when they were in the same position?"`,
          `"Is there a way we could structure this to lower the risk if it doesn't work out the way you're hoping?"`,
        ],
        dontSay: [
          `"You've been thinking about this for weeks -- it's time to just commit." -- pressure at the close is the fastest way to lose the deal.`,
          `"I guarantee you won't regret it." -- vague reassurances aren't specific enough to address fear.`,
          `Ignoring the hesitation and pushing to sign -- a reluctant close becomes a cancellation or a bad reference.`,
        ],
        objectives: [
          `Surface the specific fear behind a vague "I'm not sure" without pushing`,
          `Distinguish between a real concern that needs addressing and fear of commitment`,
          `Reassure through social proof and reversibility -- not through pressure`,
        ],
        tip: `Last-minute cold feet usually isn't about the product -- it's about the risk of being wrong. Make the decision feel safer, not add more pressure: "What's the specific thing you're hesitant about? I want to make sure you're going in with full confidence." Then reduce the perceived risk.`,
        scenario: 'closing',
        subScenarioIndex: 1,
        difficulty: 'medium',
        passScore: 7.5,
        minExchanges: 5,
      },
      {
        id: 'c8-objection-stacking',
        title: 'Closing Against Objection Stacking',
        concept: 'Stop a prospect from raising infinite last-minute objections by isolating and closing the final one',
        lessonBody: `When every objection you answer is replaced by a new one, stop addressing them individually. Name the pattern. Force a commitment that ties the close to resolving the real issue -- not addressing objection #7. Use a conditional close: "If we solve X, do we have a deal?" This transforms objection handling into a final close.`,
        doSay: [
          `"We've addressed pricing, timing, and the integration question. If those were all off the table, would we have a deal?"`,
          `"I want to make sure we're working on the real concern -- what's the one thing that, if resolved, would make this a yes?"`,
          `"If I can get you [specific resolution], are you in?"`,
        ],
        dontSay: [
          `"Okay, let me address that one too." -- answering objection after objection with infinite patience rewards the pattern.`,
          `"I'm not sure why you keep raising new concerns." -- pointing out the pattern defensively creates conflict.`,
          `Discounting to resolve the stack -- price reductions don't fix process stalls.`,
        ],
        objectives: [
          `Isolate the final real objection using a "is that the only thing?" question`,
          `Refuse to address a new objection before explicitly agreeing that all prior ones are resolved`,
          `Use a conditional close to transform the objection into a commitment`,
        ],
        tip: `When every objection you answer is replaced by a new one, stop addressing them individually. Name the pattern: "We've addressed pricing, timing, and the integration question. If those were all off the table, would we have a deal?" Force a binary moment.`,
        scenario: 'closing',
        subScenarioIndex: 2,
        difficulty: 'hard',
        passScore: 8.0,
        minExchanges: 6,
      },
      {
        id: 'c9-hard-close',
        title: 'Closing the Hard Prospect',
        concept: 'Take deliberate control of the conversation when a prospect keeps deferring and stalling',
        lessonBody: `A perpetually stalling prospect is often waiting to be led. Stop addressing individual objections and step back to the meta level: "What's really standing between us and a decision?" Then make a direct ask. The prospect who won't commit to a specific next step usually can't buy. Know when to close hard -- and when to qualify out.`,
        doSay: [
          `"I've appreciated all our conversations. I want to be straight with you -- what's really standing between us and a decision?"`,
          `"Here's what I'd like to do: [specific next step with a date]. Does that work for you?"`,
          `"At this point, I want to ask you directly -- is there a version of this that works for you, or should we be honest that it's not the right fit right now?"`,
        ],
        dontSay: [
          `"No rush, take your time." -- patience without a deadline is just a stall with your permission.`,
          `"I'll follow up again next month." -- indefinite follow-ups without forcing a decision waste everyone's time.`,
          `Continuing to send materials, answer questions, and hold calls with no commitment ask -- activity without a close is just lost time.`,
        ],
        objectives: [
          `Identify the real blocker behind a pattern of stalling -- decision authority, risk aversion, or no real intent`,
          `Make a direct ask for commitment without apologizing for it`,
          `Handle the "I need more time" response with a specific, time-bound counter`,
        ],
        tip: `A perpetually stalling prospect is often waiting to be led. Stop addressing individual objections and step back: "What's really standing between us and a decision?" Then make the ask directly. The prospect who won't commit to a specific step usually can't buy. Know when to qualify out.`,
        scenario: 'closing',
        subScenarioIndex: 2,
        difficulty: 'hard',
        passScore: 8.0,
        minExchanges: 6,
      },
    ],
  },
];

export const ALL_LESSONS = CURRICULUM.flatMap(m => m.lessons);
